/* To avoid CSS expressions while still supporting IE 7 and IE 6, use this script */
/* The script tag referencing this file must be placed before the ending body tag. */

/* Use conditional comments in order to target IE 7 and older:
	<!--[if lt IE 8]><!-->
	<script src="ie7/ie7.js"></script>
	<!--<![endif]-->
*/

(function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'icomoon\'">' + entity + '</span>' + html;
	}
	var icons = {
		'icon-globe': '&#xe994;',
		'icon-calendar': '&#xe98d;',
		'icon-bolt': '&#xe970;',
		'icon-book1': '&#xe971;',
		'icon-briefcase1': '&#xe972;',
		'icon-bug1': '&#xe973;',
		'icon-building': '&#xe974;',
		'icon-bullseye': '&#xe975;',
		'icon-calendar1': '&#xe976;',
		'icon-cart1': '&#xe977;',
		'icon-gear1': '&#xe978;',
		'icon-help': '&#xe979;',
		'icon-home2': '&#xe97a;',
		'icon-info2': '&#xe97b;',
		'icon-lightbulb': '&#xe97c;',
		'icon-mail1': '&#xe97d;',
		'icon-message': '&#xe97e;',
		'icon-news': '&#xe97f;',
		'icon-plane': '&#xe980;',
		'icon-saturn': '&#xe981;',
		'icon-send': '&#xe982;',
		'icon-server': '&#xe983;',
		'icon-truck1': '&#xe984;',
		'icon-union': '&#xe985;',
		'icon-bank': '&#xe986;',
		'icon-question-box': '&#xe993;',
		'icon-call': '&#xe992;',
		'icon-new-ticket': '&#xe991;',
		'icon-png': '&#xe990;',
		'icon-zip': '&#xe98f;',
		'icon-onboarding-check': '&#xe98e;',
		'icon-success': '&#xe98c;',
		'icon-chart-of-accounts': '&#xe988;',
		'icon-account-mapping': '&#xe987;',
		'icon-disconnected': '&#xe989;',
		'icon-sync': '&#xe98a;',
		'icon-sync-alert': '&#xe98b;',
		'icon-clear': '&#xe96f;',
		'icon-share': '&#xe96e;',
		'icon-star': '&#xe96d;',
		'icon-integration': '&#xe96c;',
		'icon-csv': '&#xe969;',
		'icon-xlsx2': '&#xe968;',
		'icon-xls2': '&#xe96a;',
		'icon-pdf': '&#xe96b;',
		'icon-bookings': '&#xe967;',
		'icon-currency-circle': '&#xe966;',
		'icon-plans': '&#xe965;',
		'icon-vendor2': '&#xe964;',
		'icon-dashboard2': '&#xe962;',
		'icon-devices': '&#xe963;',
		'icon-left-arrow': '&#xe960;',
		'icon-right-arrow': '&#xe961;',
		'icon-inventory': '&#xeb4d;',
		'icon-options': '&#xeb4c;',
		'icon-register-report': '&#xeb4b;',
		'icon-account-settings': '&#xe908;',
		'icon-questions': '&#xe92a;',
		'icon-taxes': '&#xe900;',
		'icon-credits': '&#xe901;',
		'icon-receipt': '&#xe902;',
		'icon-notification': '&#xe903;',
		'icon-check': '&#x31;',
		'icon-arrow-left': '&#x61;',
		'icon-arrow-down': '&#x63;',
		'icon-home': '&#x64;',
		'icon-arrow-right': '&#x65;',
		'icon-asterisk': '&#x6b;',
		'icon-plus': '&#x70;',
		'icon-remove': '&#x72;',
		'icon-warning': '&#x77;',
		'icon-burger-cup': '&#x7a;',
		'icon-notification-bell': '&#xe904;',
		'icon-pencil': '&#xe905;',
		'icon-nfc-tag': '&#xe906;',
		'icon-check-only': '&#xe907;',
		'icon-download': '&#xe909;',
		'icon-eye-open': '&#xe90a;',
		'icon-card': '&#xe90b;',
		'icon-info': '&#xe90c;',
		'icon-arrow-diagonal-right': '&#xe90d;',
		'icon-divide': '&#xe90e;',
		'icon-sort-ascending': '&#xe90f;',
		'icon-sort-descending': '&#xe910;',
		'icon-bottle': '&#xe911;',
		'icon-menu-filter': '&#xe912;',
		'icon-empty-search-image': '&#xe913;',
		'icon-caret-down': '&#xe914;',
		'icon-cups': '&#xe915;',
		'icon-dashboard': '&#xe916;',
		'icon-device': '&#xe917;',
		'icon-double-quote': '&#xe918;',
		'icon-xls': '&#xe919;',
		'icon-xlsx': '&#xe91a;',
		'icon-discount': '&#xe91b;',
		'icon-sort-off': '&#xe91c;',
		'icon-document': '&#xe91d;',
		'icon-discount-circle': '&#xe91e;',
		'icon-voucher-circle': '&#xe91f;',
		'icon-limit': '&#xe920;',
		'icon-eye-close': '&#xe921;',
		'icon-gear': '&#xe922;',
		'icon-guest': '&#xe923;',
		'icon-minus': '&#xe924;',
		'icon-shirt': '&#xe925;',
		'icon-staff': '&#xe926;',
		'icon-transactions': '&#xe927;',
		'icon-vendor': '&#xe928;',
		'icon-voucher': '&#xe929;',
		'icon-cash': '&#xe92b;',
		'icon-credit-card': '&#xe92c;',
		'icon-others-payment': '&#xe92d;',
		'icon-drag': '&#xe92e;',
		'icon-trash': '&#xe92f;',
		'icon-cancel': '&#xe930;',
		'icon-nfc-tag1': '&#xe931;',
		'icon-check1': '&#x32;',
		'icon-arrow-left1': '&#x62;',
		'icon-arrow-down1': '&#x66;',
		'icon-home1': '&#x67;',
		'icon-arrow-right1': '&#x68;',
		'icon-asterisk1': '&#x6c;',
		'icon-plus1': '&#x71;',
		'icon-remove1': '&#x73;',
		'icon-warning1': '&#x78;',
		'icon-burger-cup1': '&#x7b;',
		'icon-notification-bell1': '&#xe932;',
		'icon-pencil1': '&#xe933;',
		'icon-nfc-tag2': '&#xe934;',
		'icon-check-only1': '&#xe935;',
		'icon-account1': '&#xe936;',
		'icon-download1': '&#xe937;',
		'icon-eye-open1': '&#xe938;',
		'icon-card1': '&#xe939;',
		'icon-info1': '&#xe93a;',
		'icon-arrow-diagonal-right1': '&#xe93b;',
		'icon-divide1': '&#xe93c;',
		'icon-sort-ascending1': '&#xe93d;',
		'icon-sort-descending1': '&#xe93e;',
		'icon-bottle1': '&#xe93f;',
		'icon-menu-filter1': '&#xe940;',
		'icon-empty-search-image1': '&#xe941;',
		'icon-caret-down1': '&#xe942;',
		'icon-cups1': '&#xe943;',
		'icon-dashboard1': '&#xe944;',
		'icon-device1': '&#xe945;',
		'icon-double-quote1': '&#xe946;',
		'icon-xls1': '&#xe947;',
		'icon-xlsx1': '&#xe948;',
		'icon-discount1': '&#xe949;',
		'icon-sort-off1': '&#xe94a;',
		'icon-document1': '&#xe94b;',
		'icon-discount-circle1': '&#xe94c;',
		'icon-voucher-circle1': '&#xe94d;',
		'icon-limit1': '&#xe94e;',
		'icon-eye-close1': '&#xe94f;',
		'icon-gear11': '&#xe950;',
		'icon-guest1': '&#xe951;',
		'icon-minus1': '&#xe952;',
		'icon-shirt1': '&#xe953;',
		'icon-staff1': '&#xe954;',
		'icon-transactions1': '&#xe955;',
		'icon-vendor1': '&#xe956;',
		'icon-voucher1': '&#xe957;',
		'icon-folder1': '&#xe958;',
		'icon-cash1': '&#xe959;',
		'icon-credit-card1': '&#xe95a;',
		'icon-others-payment1': '&#xe95b;',
		'icon-drag1': '&#xe95c;',
		'icon-trash1': '&#xe95d;',
		'icon-cancel1': '&#xe95e;',
		'icon-nfc-tag11': '&#xe95f;',
		'0': 0
		},
		els = document.getElementsByTagName('*'),
		i, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		c = el.className;
		c = c.match(/icon-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
}());
